// Country name to flag image mapping
const countryToFlagCode = {
  'Afghanistan': 'AF',
  'Albania': 'AL',
  'Algeria': 'DZ',
  'Andorra': 'AD',
  'Angola': 'AO',
  'Antigua and Barbuda': 'AG',
  'Argentina': 'AR',
  'Armenia': 'AM',
  'Australia': 'AU',
  'Austria': 'AT',
  'Azerbaijan': 'AZ',
  'Bahamas': 'BS',
  'Bahrain': 'BH',
  'Bangladesh': 'BD',
  'Barbados': 'BB',
  'Belarus': 'BY',
  'Belgium': 'BE',
  'Belize': 'BZ',
  'Benin': 'BJ',
  'Bhutan': 'BT',
  'Bolivia': 'BO',
  'Bosnia and Herzegovina': 'BA',
  'Botswana': 'BW',
  'Brazil': 'BR',
  'Brunei': 'BN',
  'Bulgaria': 'BG',
  'Burkina Faso': 'BF',
  'Burundi': 'BI',
  'Cambodia': 'KH',
  'Cameroon': 'CM',
  'Canada': 'CA',
  'Cape Verde': 'CV',
  'Central African Republic': 'CF',
  'Chad': 'TD',
  'Chile': 'CL',
  'China': 'CN',
  'Colombia': 'CO',
  'Comoros': 'KM',
  'Congo': 'CG',
  'Costa Rica': 'CR',
  'Croatia': 'HR',
  'Cuba': 'CU',
  'Cyprus': 'CY',
  'Czech Republic': 'CZ',
  'Czechia': 'CZ',
  'Denmark': 'DK',
  'Djibouti': 'DJ',
  'Dominica': 'DM',
  'Dominican Republic': 'DO',
  'East Timor': 'TL',
  'Ecuador': 'EC',
  'Egypt': 'EG',
  'El Salvador': 'SV',
  'Equatorial Guinea': 'GQ',
  'Eritrea': 'ER',
  'Estonia': 'EE',
  'Eswatini': 'SZ',
  'Ethiopia': 'ET',
  'Fiji': 'FJ',
  'Finland': 'FI',
  'France': 'FR',
  'Gabon': 'GA',
  'Gambia': 'GM',
  'Georgia': 'GE',
  'Germany': 'DE',
  'Ghana': 'GH',
  'Greece': 'GR',
  'Grenada': 'GD',
  'Guatemala': 'GT',
  'Guinea': 'GN',
  'Guinea-Bissau': 'GW',
  'Guyana': 'GY',
  'Haiti': 'HT',
  'Honduras': 'HN',
  'Hungary': 'HU',
  'Iceland': 'IS',
  'India': 'IN',
  'Indonesia': 'ID',
  'Iran': 'IR',
  'Iraq': 'IQ',
  'Ireland': 'IE',
  'Israel': 'IL',
  'Italy': 'IT',
  'Ivory Coast': 'CI',
  'Jamaica': 'JM',
  'Japan': 'JP',
  'Jordan': 'JO',
  'Kazakhstan': 'KZ',
  'Kenya': 'KE',
  'Kiribati': 'KI',
  'Kuwait': 'KW',
  'Kyrgyzstan': 'KG',
  'Laos': 'LA',
  'Latvia': 'LV',
  'Lebanon': 'LB',
  'Lesotho': 'LS',
  'Liberia': 'LR',
  'Libya': 'LY',
  'Liechtenstein': 'LI',
  'Lithuania': 'LT',
  'Luxembourg': 'LU',
  'Madagascar': 'MG',
  'Malawi': 'MW',
  'Malaysia': 'MY',
  'Maldives': 'MV',
  'Mali': 'ML',
  'Malta': 'MT',
  'Marshall Islands': 'MH',
  'Mauritania': 'MR',
  'Mauritius': 'MU',
  'Mexico': 'MX',
  'Micronesia': 'FM',
  'Moldova': 'MD',
  'Monaco': 'MC',
  'Mongolia': 'MN',
  'Montenegro': 'ME',
  'Morocco': 'MA',
  'Mozambique': 'MZ',
  'Myanmar': 'MM',
  'Namibia': 'NA',
  'Nauru': 'NR',
  'Nepal': 'NP',
  'Netherlands': 'NL',
  'New Zealand': 'NZ',
  'Nicaragua': 'NI',
  'Niger': 'NE',
  'Nigeria': 'NG',
  'North Korea': 'KP',
  'North Macedonia': 'MK',
  'Norway': 'NO',
  'Oman': 'OM',
  'Pakistan': 'PK',
  'Palau': 'PW',
  'Panama': 'PA',
  'Papua New Guinea': 'PG',
  'Paraguay': 'PY',
  'Peru': 'PE',
  'Philippines': 'PH',
  'Poland': 'PL',
  'Portugal': 'PT',
  'Qatar': 'QA',
  'Romania': 'RO',
  'Russia': 'RU',
  'Rwanda': 'RW',
  'Saint Kitts and Nevis': 'KN',
  'Saint Lucia': 'LC',
  'Saint Vincent and the Grenadines': 'VC',
  'Samoa': 'WS',
  'San Marino': 'SM',
  'Sao Tome and Principe': 'ST',
  'Saudi Arabia': 'SA',
  'Senegal': 'SN',
  'Serbia': 'RS',
  'Seychelles': 'SC',
  'Sierra Leone': 'SL',
  'Singapore': 'SG',
  'Slovakia': 'SK',
  'Slovenia': 'SI',
  'Solomon Islands': 'SB',
  'Somalia': 'SO',
  'South Africa': 'ZA',
  'South Korea': 'KR',
  'South Sudan': 'SS',
  'Spain': 'ES',
  'Sri Lanka': 'LK',
  'Sudan': 'SD',
  'Suriname': 'SR',
  'Sweden': 'SE',
  'Switzerland': 'CH',
  'Syria': 'SY',
  'Taiwan': 'TW',
  'Tajikistan': 'TJ',
  'Tanzania': 'TZ',
  'Thailand': 'TH',
  'Togo': 'TG',
  'Tonga': 'TO',
  'Trinidad and Tobago': 'TT',
  'Tunisia': 'TN',
  'Turkey': 'TR',
  'Turkmenistan': 'TM',
  'Tuvalu': 'TV',
  'Uganda': 'UG',
  'Ukraine': 'UA',
  'United Arab Emirates': 'AE',
  'United Kingdom': 'GB',
  'United States': 'US',
  'Uruguay': 'UY',
  'Uzbekistan': 'UZ',
  'Vanuatu': 'VU',
  'Vatican City': 'VA',
  'Venezuela': 'VE',
  'Vietnam': 'VN',
  'Yemen': 'YE',
  'Zambia': 'ZM',
  'Zimbabwe': 'ZW'
};

// Function to get flag image URL from country name
export const getCountryFlag = (countryName) => {
  if (!countryName) return null;
  
  // Try exact match first
  if (countryToFlagCode[countryName]) {
    return `https://flagcdn.com/w40/${countryToFlagCode[countryName].toLowerCase()}.png`;
  }
  
  // Try case-insensitive match
  const normalizedCountry = countryName.toLowerCase();
  for (const [country, code] of Object.entries(countryToFlagCode)) {
    if (country.toLowerCase() === normalizedCountry) {
      return `https://flagcdn.com/w40/${code.toLowerCase()}.png`;
    }
  }
  
  // Try partial match for common variations
  const partialMatches = {
    'usa': 'US',
    'united states': 'US',
    'uk': 'GB',
    'united kingdom': 'GB',
    'great britain': 'GB',
    'england': 'GB',
    'scotland': 'GB',
    'wales': 'GB',
    'northern ireland': 'GB',
    'holland': 'NL',
    'the netherlands': 'NL',
    'swiss': 'CH',
    'switzerland': 'CH',
    'french': 'FR',
    'france': 'FR',
    'german': 'DE',
    'germany': 'DE',
    'italian': 'IT',
    'italy': 'IT',
    'spanish': 'ES',
    'spain': 'ES',
    'portuguese': 'PT',
    'portugal': 'PT',
    'danish': 'DK',
    'denmark': 'DK',
    'swedish': 'SE',
    'sweden': 'SE',
    'norwegian': 'NO',
    'norway': 'NO',
    'finnish': 'FI',
    'finland': 'FI',
    'icelandic': 'IS',
    'iceland': 'IS',
    'polish': 'PL',
    'poland': 'PL',
    'czech': 'CZ',
    'czech republic': 'CZ',
    'czechia': 'CZ',
    'slovak': 'SK',
    'slovakia': 'SK',
    'hungarian': 'HU',
    'hungary': 'HU',
    'romanian': 'RO',
    'romania': 'RO',
    'bulgarian': 'BG',
    'bulgaria': 'BG',
    'croatian': 'HR',
    'croatia': 'HR',
    'serbian': 'RS',
    'serbia': 'RS',
    'slovenian': 'SI',
    'slovenia': 'SI',
    'bosnian': 'BA',
    'bosnia': 'BA',
    'montenegrin': 'ME',
    'montenegro': 'ME',
    'macedonian': 'MK',
    'macedonia': 'MK',
    'albanian': 'AL',
    'albania': 'AL',
    'greek': 'GR',
    'greece': 'GR',
    'turkish': 'TR',
    'turkey': 'TR',
    'russian': 'RU',
    'russia': 'RU',
    'ukrainian': 'UA',
    'ukraine': 'UA',
    'belarusian': 'BY',
    'belarus': 'BY',
    'moldovan': 'MD',
    'moldova': 'MD',
    'estonian': 'EE',
    'estonia': 'EE',
    'latvian': 'LV',
    'latvia': 'LV',
    'lithuanian': 'LT',
    'lithuania': 'LT',
    'canadian': 'CA',
    'canada': 'CA',
    'australian': 'AU',
    'australia': 'AU',
    'new zealand': 'NZ',
    'japanese': 'JP',
    'japan': 'JP',
    'chinese': 'CN',
    'china': 'CN',
    'korean': 'KR',
    'south korea': 'KR',
    'thai': 'TH',
    'thailand': 'TH',
    'vietnamese': 'VN',
    'vietnam': 'VN',
    'indonesian': 'ID',
    'indonesia': 'ID',
    'malaysian': 'MY',
    'malaysia': 'MY',
    'singaporean': 'SG',
    'singapore': 'SG',
    'filipino': 'PH',
    'philippines': 'PH',
    'indian': 'IN',
    'india': 'IN',
    'pakistani': 'PK',
    'pakistan': 'PK',
    'bangladeshi': 'BD',
    'bangladesh': 'BD',
    'sri lankan': 'LK',
    'sri lanka': 'LK',
    'nepali': 'NP',
    'nepal': 'NP',
    'brazilian': 'BR',
    'brazil': 'BR',
    'argentine': 'AR',
    'argentina': 'AR',
    'chilean': 'CL',
    'chile': 'CL',
    'peruvian': 'PE',
    'peru': 'PE',
    'colombian': 'CO',
    'colombia': 'CO',
    'venezuelan': 'VE',
    'venezuela': 'VE',
    'ecuadorian': 'EC',
    'ecuador': 'EC',
    'bolivian': 'BO',
    'bolivia': 'BO',
    'paraguayan': 'PY',
    'paraguay': 'PY',
    'uruguayan': 'UY',
    'uruguay': 'UY',
    'guyanese': 'GY',
    'guyana': 'GY',
    'surinamese': 'SR',
    'suriname': 'SR',
    'mexican': 'MX',
    'mexico': 'MX',
    'guatemalan': 'GT',
    'guatemala': 'GT',
    'belizean': 'BZ',
    'belize': 'BZ',
    'honduran': 'HN',
    'honduras': 'HN',
    'salvadoran': 'SV',
    'el salvador': 'SV',
    'nicaraguan': 'NI',
    'nicaragua': 'NI',
    'costa rican': 'CR',
    'costa rica': 'CR',
    'panamanian': 'PA',
    'panama': 'PA',
    'cuban': 'CU',
    'cuba': 'CU',
    'jamaican': 'JM',
    'jamaica': 'JM',
    'haitian': 'HT',
    'haiti': 'HT',
    'dominican': 'DO',
    'dominican republic': 'DO',
    'puerto rican': 'PR',
    'puerto rico': 'PR',
    'trinidadian': 'TT',
    'trinidad and tobago': 'TT',
    'barbadian': 'BB',
    'barbados': 'BB',
    'bahamian': 'BS',
    'bahamas': 'BS',
    'antiguan': 'AG',
    'antigua and barbuda': 'AG',
    'saint lucian': 'LC',
    'saint lucia': 'LC',
    'grenadian': 'GD',
    'grenada': 'GD',
    'saint vincentian': 'VC',
    'saint vincent and the grenadines': 'VC',
    'saint kittsian': 'KN',
    'saint kitts and nevis': 'KN',
    'dominican': 'DM',
    'dominica': 'DM'
  };
  
  for (const [key, code] of Object.entries(partialMatches)) {
    if (normalizedCountry.includes(key)) {
      return `https://flagcdn.com/w40/${code.toLowerCase()}.png`;
    }
  }
  
  // Return null if no match found
  return null;
};

// Function to get flag image with country name
export const getCountryFlagWithName = (countryName) => {
  const flagUrl = getCountryFlag(countryName);
  return { flagUrl, countryName };
}; 